use std::ffi::OsStr;
use std::io::Write;
use std::path::PathBuf;
use std::{collections::BTreeSet, fs::File};

use wgsl_to_wgpu::{MatrixVectorTypes, WriteOptions, create_shader_module};

fn write_header(f: &mut impl Write) -> Result<(), std::io::Error> {
    writeln!(
        f,
        "// File automatically generated by wgsl_to_wgpu in build.rs"
    )?;
    writeln!(f, "// Changes made to this file will not be saved.")?;
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut mod_file = File::create("src/shaders/mod.rs")?;
    write_header(&mut mod_file)?;

    let mut shaders = BTreeSet::<PathBuf>::new();
    for entry in std::fs::read_dir("src/shaders").expect("could not open shader directory") {
        let path = entry.expect("could not open shader directory entry").path();
        if path.extension().and_then(OsStr::to_str) == Some("wgsl") {
            shaders.insert(path);
        }
    }

    for wgsl_file in shaders.into_iter() {
        let wgsl_source = std::fs::read_to_string(&wgsl_file)?;
        println!(
            "cargo:rerun-if-changed={}",
            wgsl_file
                .to_str()
                .expect("could not convert filename to string")
        );

        let name = wgsl_file
            .file_prefix()
            .expect("could not get filename")
            .to_str()
            .expect("could not convert filename to string");

        let mut rust_file = wgsl_file.clone();
        rust_file.set_extension("rs");
        let mut rust_file = File::create(rust_file).expect("could not open rust file");
        write_header(&mut rust_file)?;
        writeln!(&mut rust_file, "#![allow(dead_code, non_snake_case)]")?;

        let text = &create_shader_module(
            &wgsl_source,
            &format!("{name}.wgsl"),
            WriteOptions {
                derive_bytemuck_vertex: true,
                derive_bytemuck_host_shareable: true,
                matrix_vector_types: MatrixVectorTypes::Glam,
                rustfmt: true,
                validate: Some(Default::default()),
                ..Default::default()
            },
        )
        .inspect_err(|error| error.emit_to_stderr_with_path(&wgsl_source, &wgsl_file))
        .map_err(|_| "Failed to validate shader")?;

        writeln!(&mut rust_file, "{}", text)?;
        writeln!(&mut mod_file, "pub mod {name};")?;
    }

    Ok(())
}
