[package]
name = "physarum-36p-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "physarum"
path = "src/main.rs"

[dependencies]
env_logger = "0.11.8"
pollster = "0.4.0"
wgpu = "26.0"
winit = "0.30"
