[package]
name = "physarum-36p-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "physarum"
path = "src/main.rs"

[dependencies]
bytemuck = "1.23.2"
env_logger = "0.11"
pollster = "0.4"
rand = "0.9"
wgpu = { version = "26.0" }
winit = "0.30"
